element:
- style: tabpanel
  id: sfincs
  position:
    x: 10
    y: 10
    width: -10
    height: -10
  variable_group: sfincs
  tab:
  - string: Domain
    module: models.sfincs.ddb_sfincs_domain
    element: sfincs.domain.yml
  - string: Time Frame
    module: models.sfincs.ddb_sfincs_timeframe
    element: sfincs.timeframe.yml
  - string: Physics
    element: sfincs.physics.yml
  - string: Numerics
    module: models.sfincs.ddb_sfincs_numerics
    element: sfincs.numerics.yml
  - string: Boundary Conditions
    module: models.sfincs.ddb_sfincs_boundary_conditions
    element: sfincs.boundaryconditions.yml
  - string: Waves
    element: sfincs.waves.yml
  - string: Meteo
    module: models.sfincs.ddb_sfincs_meteo
    element: sfincs.meteo.yml
  - string: Structures
    module: models.sfincs.ddb_sfincs_structures
    element: sfincs.structures.yml
  - string: Output
    module: models.sfincs.ddb_sfincs_output
    element: sfincs.output.yml
- style: mapbox
