element:
- style: tabpanel
  id: sfincs
  position:
    x: 10
    y: 10
    width: -10
    height: -10
  variable_group: sfincs
  tab:
  - string: Domain
    module: models.sfincs.domain
    element: domain.yml
  - string: Time Frame
    module: models.sfincs.timeframe
    element: timeframe.yml
  - string: Physics
    element: physics.yml
  - string: Numerics
    module: models.sfincs.numerics
    element: numerics.yml
  - string: Boundary Conditions
    module: models.sfincs.boundary_conditions
    element: boundary_conditions.yml
  - string: Waves
    element: waves.yml
  - string: Meteo
    module: models.sfincs.meteo
    element: meteo.yml
  - string: Structures
    module: models.sfincs.structures
    element: structures.yml
  - string: Output
    module: models.sfincs.output
    element: output.yml
- style: mapbox
