element:
- style: tabpanel
  position:
    x: 10
    y: 10
    width: -10
    height: 160
  tab:
  - string: SnapWave
    element: sfincs.waves.snapwave.yml
  - string: Wave Makers
    element: sfincs.waves.wavemakers.yml
