element:
- style: edit
  position:
    x: 60
    y: 110
    width: 60
    height: 20
  text: X0
  variable: x0
  method: edit
- style: edit
  position:
    x: 160
    y: 110
    width: 60
    height: 20
  text: Y0
  variable: y0
  method: edit
- style: edit
  position:
    x: 60
    y: 85
    width: 60
    height: 20
  text: MMax
  variable: mmax
- style: edit
  position:
    x: 160
    y: 85
    width: 60
    height: 20
  text: NMax
  variable: nmax
- style: edit
  position:
    x: 60
    y: 60
    width: 60
    height: 20
  text: dX
  variable: dx
- style: edit
  position:
    x: 160
    y: 60
    width: 60
    height: 20
  text: dY
  variable: dy
- style: edit
  position:
    x: 60
    y: 35
    width: 60
    height: 20
  text: Rotation
  variable: rotation
- style: pushbutton
  text: Draw Layout
  position:
    x: 230
    y: 110
    width: 120
    height: 20
  method: draw_grid_outline
- style: pushbutton
  text: Generate Grid
  position:
    x: 230
    y: 85
    width: 120
    height: 20
  method: generate_grid
