name: Documentation Improvement
description: Report wrong or missing documentation
labels: ["documentation"]

body:
  - type: checkboxes
    id: issue-check
    attributes:
      label: Preliminary Checklist
      description: "Before submitting this documentation request, please ensure the following criteria are met:"
      options:
        - label: "I have searched the existing issues list for similar requests and found none. If you did find a similar requests, please add a comment to the existing requests instead of opening a new one."
    validations:
      required: true

  - type: dropdown
    id: kind
    attributes:
      description: What kind of documentation issue is this?
      label: Kind of issue
      options:
        - Docs are wrong
        - Docs are unclear
        - Docs are missing
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      description: >
        If the docs are wrong or unclear please provide the URL of the documentation in question
      label: Location of the documentation

  - type: textarea
    id: problem
    attributes:
      description: >
        Please provide a description of the documentation problem
      label: Documentation problem
    validations:
      required: true
      
  - type: textarea
    id: suggested-fix
    attributes:
      description: >
        Please explain your suggested fix and why it's better than the existing documentation
      label: Suggested fix for documentation
