name: Feature Request
description: Suggest an idea/enhancement for this project
labels: enhancement, question

body:
  - type: dropdown
    id: checks
    attributes:
      description: What kind of feature request is this?
      label: Kind of request
      options:
        - Adding new functionality
        - Changing existing functionality
        - Removing existing functionality
  
  - type: textarea
    id: description
    attributes:
      description: >
        Please provide a clear and concise description of the feature you're requesting
      label: Enhancement Description
    validations:
      required: true
  
  - type: textarea
    id: task-list
    attributes:
      description: >
        Please provide a list of tasks that need to be completed before this issue can be closed. 
      label: Task list
    validations:
      required: true
  
  - type: textarea
    id: use-case
    attributes:
      description: >
        Please describe a situation in which this feature would be useful to you, with code or cli examples if possible
      label: Use case
  
  - type: textarea
    id: context
    attributes:
      description: >
        Please add any other context or screenshots about the feature request here. You can select the textbox and 'Paste, drop or click to add files' to attach them to this request.
      label: Additional Context
