name: Bug Report - User
description: Report incorrect behavior 
labels: [user bug]

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report Guide
        Thank you for taking the time to report a bug. Your contribution is essential to improve FloodAdapt. Please provide as much detail as possible to help us understand and address the issue. Complete all the required fields and consider attaching screenshots or logs if they can help explain the problem.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: >
        Please select the severity level of the bug.
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
  
  - type: textarea
    id: steps-to-reproduce
    attributes:
      description: >
        Please provide a list of steps to reproduce the bug, starting from the initial state of the application.
      label: Steps to reproduce
    validations:
      required: true
  
  - type: textarea
    id: current-behaviour
    attributes:
      description: >
        Please provide a description or screenshots of the incorrect behaviour achieved by following the steps to reproduce
      label: Current behaviour
    validations:
      required: true
  
  - type: textarea
    id: expected-behaviour
    attributes:
      description: >
        Please provide a description of what you think the behaviour should be
      label: Desired behaviour
    validations:
      required: true
  
  - type: file
    id: attachments
    attributes:
      label: Attachments
      description: >
        If applicable, attach any screenshots, logs, or code
