element:
- style: panel
  position:
    x: 10
    y: 10
    width: -10
    height: 160
  element:
  - style: listbox
    position:
      x: 10
      y: 10
      width: 100
      height: 140
    text: Polygons
    method: select_polygon
    variable: active_polygon
    select: index
    option_string:
      variable: polygon_names
  - style: pushbutton
    text: Add Polygon
    position:
      x: 120
      y: 130
      width: 120
      height: 20
    method: draw_polygon
  - style: pushbutton
    text: Delete Polygon
    position:
      x: 120
      y: 105
      width: 120
      height: 20
    method: delete_polygon
