element:
- style: panel
  position:
    x: 10
    y: 10
    width: -10
    height: 160
  element:
  - style: pushbutton
    position:
      x: 10
      y: 110
      width: 130
      height: 20
    text: Add Point
    method: click_boundary_point
    tooltip: Click boundary point
