element:
- style: panel
  position:
    x: 10
    y: 10
    width: -10
    height: 160
  element:
  - style: datetimeedit
    position:
      x: 80
      y: 110
      width: 110
      height: 20
    text: Reference Time
    variable: tref
    method: set_variables
  - style: datetimeedit
    position:
      x: 80
      y: 85
      width: 110
      height: 20
    text: Start Time
    variable: tstart
    method: set_variables
  - style: datetimeedit
    position:
      x: 80
      y: 60
      width: 110
      height: 20
    text: Stop Time
    variable: tstop
    method: set_variables
  - style: edit
    position:
      x: 80
      y: 35
      width: 110
      height: 20
    text: Spin-up Time (s)
    variable: tspinup
    method: set_variables
