element:
- style: tabpanel
  id: hurrywave
  position:
    x: 10
    y: 10
    width: -10
    height: -10
  variable_group: hurrywave
  tab:
  - string: Domain
    module: models.hurrywave.domain
    method: set_variables
    element: domain.yml
  - string: Time Frame
    module: models.hurrywave.timeframe
    element: timeframe.yml
  - string: Physics
    element: physics.yml
  - string: Numerics
    module: models.hurrywave.numerics
    element: numerics.yml
  - string: Boundary Conditions
    module: models.hurrywave.boundary_conditions
    element: boundary_conditions.yml
  - string: Meteo
    module: models.hurrywave.meteo
    element: meteo.yml
  - string: Observation Points
    module: models.hurrywave.observation_points
    element: observation_points.yml
  - string: Structures
    module: models.hurrywave.structures
    element: structures.yml
  - string: Output
    module: models.hurrywave.output
    element: output.yml
