element:
- style: panel
  title: Output
  position:
    x: 10
    y: 10
    width: -10
    height: 160
  element:
  - style: edit
    position:
      x: 120
      y: 130
      width: 80
      height: 20
    tooltipstring: Edit map output interval (in seconds)
    text: Map output interval (s)
    textposition: left
    variable_group: sfincs
    variable: dtmapout
    method: set_variables
  - style: edit
    position:
      x: 120
      y: 105
      width: 80
      height: 20
    tooltipstring: Edit max output interval (in seconds)
    text: Max output interval (s)
    textposition: left
    variable_group: sfincs
    variable: dtmaxout
    method: set_variables
  - style: edit
    position:
      x: 120
      y: 80
      width: 80
      height: 20
    tooltipstring: Edit history output interval (in seconds)
    text: His output interval (s)
    textposition: left
    variable_group: sfincs
    variable: dthisout
    method: set_variables
  - style: edit
    position:
      x: 120
      y: 55
      width: 80
      height: 20
    tooltipstring: Edit restart output interval (in seconds)
    text: Restart output interval (s)
    textposition: left
    variable_group: sfincs
    variable: dtrstout
    method: set_variables
  - style: popupmenu
    position:
      x: 120
      y: 30
      width: 80
      height: 20
    text: Output Format
    variable_group: sfincs
    variable: outputformat
    method: set_variables
    option_string:
    - NetCDF
    - ASCII
    option_value:
    - net
    - asc
