element:
- style: tabpanel
  position:
    x: 10
    y: 10
    width: -10
    height: 160
  tab:
  - string: Constants
    module: models.hurrywave.physics_constants
    element: physics.constants.yml
  - string: Roughness
    module: models.hurrywave.physics_roughness
  - string: Meteo
    module: models.hurrywave.physics_meteo
    element: physics.meteo.yml
